"""Generate issue forms, labeler rules and the label list from release/packages.json."""
import argparse
import json
from pathlib import Path

from common import ROOT, inventory

HEADER = "# Generated by scripts/generate_github.py from release/packages.json. Do not edit.\n"
OTHER = "Other / not sure"
TOOLING = ["scripts/**", "Tests/**", "release/**", ".github/**", "release-please-config.json",
           ".release-please-manifest.json"]
FORMS = {
    "bug_report.yml": ("Bug report", "Report a problem in one package", "bug", [
        ("textarea", "description", "What happened?", True),
        ("textarea", "reproduction", "Steps to reproduce", True),
        ("textarea", "expected", "Expected behavior", False),
        ("input", "version", "Package version", True),
        ("textarea", "environment", "Xcode, Swift and OS versions", False)]),
    "feature_request.yml": ("Feature request", "Suggest a change to one package", "enhancement", [
        ("textarea", "problem", "What problem does this solve?", True),
        ("textarea", "proposal", "Proposed change", True),
        ("textarea", "alternatives", "Alternatives considered", False)]),
}


def q(value):
    # JSON strings are valid double-quoted YAML scalars.
    return json.dumps(value)


def form(title, description, label, fields, keys):
    lines = [HEADER.rstrip(), f"name: {q(title)}", f"description: {q(description)}", f"labels: [{q(label)}]",
             "body:", "  - type: dropdown", "    id: package", "    attributes:", f"      label: {q('Package')}",
             "      options:", *[f"        - {q(k)}" for k in [*keys, OTHER]], "    validations:", "      required: true"]
    for kind, name, text, required in fields:
        lines += [f"  - type: {kind}", f"    id: {name}", "    attributes:", f"      label: {q(text)}",
                  "    validations:", f"      required: {str(required).lower()}"]
    return "\n".join(lines) + "\n"


def labels(packages):
    result = [{"name": f"pkg:{key}", "color": "1d76db", "description": f"Package {key} ({p['path']})"}
              for key, p in sorted(packages.items())]
    return result + [{"name": "pkg:tooling", "color": "5319e7", "description": "Release tooling and CI"},
                     {"name": "from-public-repo", "color": "fbca04", "description": "Reported in a publication repository"}]


def labeler(packages):
    rules = {f"pkg:{key}": [p["path"] + "/**"] for key, p in sorted(packages.items())}
    rules["pkg:tooling"] = TOOLING
    lines = [HEADER.rstrip()]
    for name, globs in rules.items():
        lines += [f"{q(name)}:", "  - changed-files:", "      - any-glob-to-any-file:",
                  *[f"          - {q(g)}" for g in globs]]
    return "\n".join(lines) + "\n"


def generate(root=ROOT):
    packages = inventory(root)
    files = {f".github/ISSUE_TEMPLATE/{name}": form(*spec, list(packages)) for name, spec in FORMS.items()}
    files[".github/ISSUE_TEMPLATE/config.yml"] = HEADER + "blank_issues_enabled: false\n"
    files[".github/labeler.yml"] = labeler(packages)
    files[".github/labels.json"] = json.dumps(labels(packages), indent=2) + "\n"
    return files


def stale(root=ROOT):
    return [path for path, text in generate(root).items()
            if not (root / path).exists() or (root / path).read_text() != text]


def write(root=ROOT):
    changed = stale(root)
    for path, text in generate(root).items():
        if path in changed:
            (root / path).parent.mkdir(parents=True, exist_ok=True)
            (root / path).write_text(text)
    return changed


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    changed = stale() if args.check else write()
    print(json.dumps(changed))
    if args.check and changed:
        raise SystemExit("Run python3 scripts/generate_github.py and commit the generated files: " + ", ".join(changed))
