name: Experimental Release Please
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: experimental-release-please
  cancel-in-progress: false
jobs:
  intent:
    if: github.repository == 'rudderlabs/experimental-swift-monorepo' && vars.EXPERIMENTAL_RELEASES_ENABLED == 'true' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: experimental-spm-release
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
        with:
          egress-policy: audit

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        id: token
        with:
          client-id: ${{ vars.RELEASE_APP_CLIENT_ID }}
          private-key: ${{ secrets.RELEASE_PRIVATE_KEY }}
          owner: rudderlabs
          repositories: experimental-swift-monorepo
          permission-contents: write
          permission-pull-requests: write
      - uses: googleapis/release-please-action@8b8fd2cc23b2e18957157a9d923d75aa0c6f6ad5
        id: release
        with:
          token: ${{ steps.token.outputs.token }}
          target-branch: main
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
